Rails:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 30

Metrics/ModuleLength:
  Max: 250

Metrics/ClassLength:
  Max: 250

AllCops:
  TargetRubyVersion: 2.4.1
  Exclude:
    - 'config/**/*'
    - 'spec/**/*'
    - 'db/*'
    - 'bin/*'
    - 'app/channels/**/*'
    - 'app/admin/*'

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Lint/AmbiguousBlockAssociation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Layout/FirstParameterIndentation:
  EnforcedStyle: consistent